services:
  python:
    build: .
    environment:
      SELENIUM_REMOTE_URL: http://chrome:4444
    depends_on:
      - chrome
    
  chrome:
    image: selenium/standalone-chrome:130.0
    ports:
      - 7000:7900